

- name: Gather Policy Access Rule Details
  hosts: localhost
  connection: local

  vars:
    zpa_cloud:
      client_id: "{{ client_id }}"
      client_secret: "{{ client_secret | default(omit) }}"
      customer_id: "{{ customer_id | default(omit) }}"
      cloud: "{{ cloud | default(omit) }}"

  tasks:
    # zpa_policy_access_rule_info.yml
    - name: Gather Details of All Policy Access Rules
      zscaler.zpacloud.zpa_policy_access_rule_info:
        provider: "{{ zpa_cloud }}"
      register: access_rules

    - name: All Access Rules
      ansible.builtin.debug:
        msg: "{{ access_rules }}"

    # zpa_policy_access_timeout_rule_info.yml
    - name: Gather All Timeout Policy Rules
      zscaler.zpacloud.zpa_policy_access_timeout_rule_info:
        provider: "{{ zpa_cloud }}"
      register: timeout_rule

    - name: All Timeout Policy Rules
      ansible.builtin.debug:
        msg: "{{ timeout_rule }}"

    # zpa_policy_access_forwarding_rule_info.yml
    - name: Gather All Forwarding Policy
      zscaler.zpacloud.zpa_policy_access_forwarding_rule_info:
        provider: "{{ zpa_cloud }}"
      register: forwarding_rules

    - name: All Forwarding Policy
      ansible.builtin.debug:
        msg: "{{ forwarding_rules }}"        

    # zpa_app_connector_group_info.yml
    - name: Gather Details of all App Connector Groups
      zscaler.zpacloud.zpa_app_connector_group_info:
        provider: "{{ zpa_cloud }}"
      register: all_app_connectors_result
  
    - name: Debug the entire result
      ansible.builtin.debug:
        var: all_app_connectors_result 
  
    - name: Display specific details from App Connector Groups
      ansible.builtin.debug:
        msg: "{{ all_app_connectors_result.groups }}" 

    # zpa_application_segment_info.yml
    - name: Gather Details of All Application Segments
      zscaler.zpacloud.zpa_application_segment_info:
        provider: "{{ zpa_cloud }}"
      register: all_app_segments

    - name: All App Segment Details
      ansible.builtin.debug:
        msg: "{{ all_app_segments }}"     
             
    
    # zpa_service_edge_groups_info.yml
    - name: Gather Detail Information of All Service Edge Groups
      zscaler.zpacloud.zpa_service_edge_groups_info:
        provider: "{{ zpa_cloud }}"
      register: service_edge_groups

    - name: All Service Edge Groups
      ansible.builtin.debug:
        msg: "{{ service_edge_groups }}"
    
   
    # zpa_application_server_info.yml
    - name: Gather Information Details of All Application Servers
      zscaler.zpacloud.zpa_application_server_info:
        provider: "{{ zpa_cloud }}"
      register: all_app_servers

    - name: All Application Servers Details
      ansible.builtin.debug:
        msg: "{{ all_app_servers }}"


    # zpa_cloud_connector_group_info.yml
    - name: Gather Information Details of All Cloud Connector Groups
      zscaler.zpacloud.zpa_cloud_connector_group_info:
        provider: "{{ zpa_cloud }}"
      register: all_cloud_connector_groups

    - name: All Cloud Connector Groups
      ansible.builtin.debug:
        msg: "{{ all_cloud_connector_groups }}"       
                  
    # zpa_enrollment_cert_info.yml
    - name: Gather Information Details of All Enrollment Certificates
      zscaler.zpacloud.zpa_enrollement_certificate_info:
        provider: "{{ zpa_cloud }}"
      register: all_enrollment_certs

    - name: All Enrolment Certificates
      ansible.builtin.debug:
        msg: "{{ all_enrollment_certs }}"

    # zpa_machine_group_info.yml
    - name: Gather Details of All Machine Groups
      zscaler.zpacloud.zpa_machine_group_info:
        provider: "{{ zpa_cloud }}"
      register: machine_groups

    - name: All Machine Groups
      ansible.builtin.debug:
        msg: "{{ machine_groups }}"

    # zpa_posture_profile_info.yml
    - name: Gather Details of All Posture Profiles
      zscaler.zpacloud.zpa_posture_profile_info:
        provider: "{{ zpa_cloud }}"
      register: posture_profiles

    - name: All Posture Profiles
      ansible.builtin.debug:
        msg: "{{ posture_profiles }}"

    # zpa_pra_console_controller_info.yml     
    - name: Get Detail Information of All PRA Consoles
      zscaler.zpacloud.zpa_pra_console_controller_info:
        provider: "{{ zpa_cloud }}"
      register: pra_consoles

    - name: All PRA Consoles
      ansible.builtin.debug:
        msg: "{{ pra_consoles }}"
 
    # zpa_pra_portal_controller_info.yml       
    - name: Get Detail Information of All PRA Credentials
      zscaler.zpacloud.zpa_pra_portal_controller_info:
        provider: "{{ zpa_cloud }}"
      register: all_portals

    - name: All PRA Portals Details
      ansible.builtin.debug:
        msg: "{{ all_portals }}"


   # zpa_provisioning_key_info.yml part 1
    - name: Gather Details of All Connector Group Provisioning Keys
      zscaler.zpacloud.zpa_provisioning_key_info:
        provider: "{{ zpa_cloud }}"
        key_type: connector
      register: all_connector_grp_keys

    - name: All Connector Group Provisioning Keys
      ansible.builtin.debug:
        msg: "{{ all_connector_grp_keys }}"

    # zpa_provisioning_key_info.yml part 2
    - name: Gather Details of All Service Edge Group Provisioning Keys
      zscaler.zpacloud.zpa_provisioning_key_info:
        provider: "{{ zpa_cloud }}"
        key_type: service_edge
      register: all_edge_grp_key_name

    - name: All Service Edge Group
      ansible.builtin.debug:
        msg: "{{ all_edge_grp_key_name }}" 

    # zpa_segment_group_info.yml
    - name: Gather Detail Information of All Segment Groups
      zscaler.zpacloud.zpa_segment_group_info:
        provider: "{{ zpa_cloud }}"
      register: segment_groups

    - name: All Segment Groups
      ansible.builtin.debug:
        msg: "{{ segment_groups }}"


    # zpa_server_group_info.yml 
    - name: Gather Details of All Server Groups
      zscaler.zpacloud.zpa_server_group_info:
        provider: "{{ zpa_cloud }}"
      register: server_groups

    - name: All Server Groups
      ansible.builtin.debug:
        msg: "{{ server_groups }}"


    # zpa_trusted_networks_info.yml
    - name: Gather Details of All Trusted Networks
      zscaler.zpacloud.zpa_trusted_networks_info:
        provider: "{{ zpa_cloud }}"
      register: trusted_networks

    - name: All Trusted Networks
      ansible.builtin.debug:
        msg: "{{ trusted_networks }}"

        
                          