

- name: Gather Policy Access Rule Details
  hosts: localhost
  connection: local

  vars:
    zpa_cloud:
      client_id: "{{ client_id }}"
      client_secret: "{{ client_secret | default(omit) }}"
      customer_id: "{{ customer_id | default(omit) }}"
      cloud: "{{ cloud | default(omit) }}"

  tasks:
    - name: Gather Details of All Policy Access Rules
      zscaler.zpacloud.zpa_policy_access_rule_info:
        provider: "{{ zpa_cloud }}"
      register: access_rules

    - name: All Access Rules
      ansible.builtin.debug:
        msg: "{{ access_rules }}"


    - name: Gather All Timeout Policy Rules
      zscaler.zpacloud.zpa_policy_access_timeout_rule_info:
        provider: "{{ zpa_cloud }}"
      register: timeout_rule

    - name: All Timeout Policy Rules
      ansible.builtin.debug:
        msg: "{{ timeout_rule }}"


    - name: Gather All Forwarding Policy
      zscaler.zpacloud.zpa_policy_access_forwarding_rule_info:
        provider: "{{ zpa_cloud }}"
      register: forwarding_rules

    - name: All Forwarding Policy
      ansible.builtin.debug:
        msg: "{{ forwarding_rules }}"        


    - name: Gather Details of all App Connector Groups
      zscaler.zpacloud.zpa_app_connector_group_info:
        provider: "{{ zpa_cloud }}"
      register: all_app_connectors_result
  
    - name: Debug the entire result
      ansible.builtin.debug:
        var: all_app_connectors_result 
  
    - name: Display specific details from App Connector Groups
      ansible.builtin.debug:
        msg: "{{ all_app_connectors_result.groups }}" 


    - name: Gather Details of All Application Segments
      zscaler.zpacloud.zpa_application_segment_info:
        provider: "{{ zpa_cloud }}"
      register: all_app_segments

    - name: All App Segment Details
      ansible.builtin.debug:
        msg: "{{ all_app_segments }}"     
             
    ##########################################################
    - name: Gather Details of All Service Edge Groups by Name
      zscaler.zpacloud.zpa_service_edge_groups:
        provider: "{{ zpa_cloud }}"
        name: PDC Service Edge Group
      register: service_edge_group_name

    - name: Service Edge Groups by Name
      ansible.builtin.debug:
        msg: "{{ service_edge_group_name }}"    
    #########################################################

    - name: Gather Information Details of All Application Servers
      zscaler.zpacloud.zpa_application_server_info:
        provider: "{{ zpa_cloud }}"
      register: all_app_servers

    - name: All Application Servers Details
      ansible.builtin.debug:
        msg: "{{ all_app_servers }}"



    - name: Gather Information Details of All Cloud Connector Groups
      zscaler.zpacloud.zpa_cloud_connector_group_info:
        provider: "{{ zpa_cloud }}"
      register: all_cloud_connector_groups

    - name: All Cloud Connector Groups
      ansible.builtin.debug:
        msg: "{{ all_cloud_connector_groups }}"       
                  

    - name: Gather Information Details of All Enrollment Certificates
      zscaler.zpacloud.zpa_enrollement_certificate_info:
        provider: "{{ zpa_cloud }}"
      register: all_enrollment_certs

    - name: All Enrolment Certificates
      ansible.builtin.debug:
        msg: "{{ all_enrollment_certs }}"


    - name: Gather Details of All Machine Groups
      zscaler.zpacloud.zpa_machine_group_info:
        provider: "{{ zpa_cloud }}"
      register: machine_groups

    - name: All Machine Groups
      ansible.builtin.debug:
        msg: "{{ machine_groups }}"


    - name: Gather Details of All Posture Profiles
      zscaler.zpacloud.zpa_posture_profile_info:
        provider: "{{ zpa_cloud }}"
      register: posture_profiles

    - name: All Posture Profiles
      ansible.builtin.debug:
        msg: "{{ posture_profiles }}"

        
    - name: Get Detail Information of All PRA Consoles
      zscaler.zpacloud.zpa_pra_console_controller_info:
        provider: "{{ zpa_cloud }}"
      register: pra_consoles

    - name: All PRA Consoles
      ansible.builtin.debug:
        msg: "{{ pra_consoles }}"

        
    - name: Get Detail Information of All PRA Credentials
      zscaler.zpacloud.zpa_pra_portal_controller_info:
        provider: "{{ zpa_cloud }}"
      register: all_portals

    - name: All PRA Portals Details
      ansible.builtin.debug:
        msg: "{{ all_portals }}"



