- name: Gather Details of Service Edge Groups
  hosts: localhost
  connection: local

  vars:
    zpa_cloud:
      client_id: "{{ client_id }}"
      client_secret: "{{ client_secret | default(omit) }}"
      customer_id: "{{ customer_id | default(omit) }}"
      cloud: "{{ cloud | default(omit) }}"

  tasks:
    - name: Gather Details of Service Edge Groups (All)
      zscaler.zpacloud.zpa_service_edge_groups:
        provider: "{{ zpa_cloud }}"
        name: ""
      register: zpa_service_edge_groups

    - name: Display All Service Edge Groups
      ansible.builtin.debug:
        msg: "{{ zpa_service_edge_groups }}"

#    - name: Gather Details of Service Edge Groups by Name
#      zscaler.zpacloud.zpa_service_edge_groups:
#        provider: "{{ zpa_cloud }}"
#        name: "Example"
#      register: service_edge_group_name

#    - name: Display Service Edge Groups by Name
#      ansible.builtin.debug:
#        msg: "{{ service_edge_group_name }}"

#    - name: Gather Details of Service Edge Groups by ID
#      zscaler.zpacloud.zpa_service_edge_groups:
#        provider: "{{ zpa_cloud }}"
#        id: "216196257331291969"
#      register: service_edge_group_id

#    - name: Display Service Edge Groups by ID
#      ansible.builtin.debug:
#        msg: "{{ service_edge_group_id }}"
