---
# zpa_trusted_network_info.yml - Get details (ID and/or Name) of a Trusted Network resource.
#
# Description
# ===========
#
# Quick example of how to use the 'zpa_trusted_network_info' module to retrieve a Trusted Network
# details from the ZPA Cloud.
#
# This playbook requires proper API credentials to be passed statically or via environment variables
# for connection to the ZPA Cloud 'client_id', 'client_secret', customer_id and 'cloud'
# These may be defined as host variables (see `host_vars/zpa_cloud.yml` for an example) or
# extra vars.
#
# Modules Used
# ============
#
# zpa_trusted_network_info - https://zscaler.github.io/zpacloud-ansible/modules/zpa_trusted_network_info_module.html
#
# Usage
# =====
#
#  $ ansible-playbook zpa_trusted_network_info.yml

- name: Gather Trusted Network Details
  hosts: localhost
  connection: local

  vars:
    zpa_cloud:
      client_id: "{{ client_id }}"
      client_secret: "{{ client_secret | default(omit) }}"
      customer_id: "{{ customer_id | default(omit) }}"
      cloud: "{{ cloud | default(omit) }}"

  tasks:
    # Gather all Trusted Network Info
    - name: Gather Details of All Trusted Networks
      zscaler.zpacloud.zpa_trusted_networks_info:
        provider: "{{ zpa_cloud }}"
      register: trusted_networks

    - name: All Trusted Networks
      ansible.builtin.debug:
        msg: "{{ trusted_networks }}"

    # Gather Specific Trusted Network Info By Name
#    - name: Gather Details of a Specific Trusted Network by Name
#      zscaler.zpacloud.zpa_trusted_networks_info:
#        provider: "{{ zpa_cloud }}"
#        name: Corp-Trusted-Networks
#      register: trusted_network_name

#    - name: Trusted Networks by Name
#      ansible.builtin.debug:
#        msg: "{{ trusted_network_name }}"

    # Gather Specific Trusted Network Info By ID
#    - name: Gather Details of a Specific Trusted Network by ID
#      zscaler.zpacloud.zpa_trusted_networks_info:
#        provider: "{{ zpa_cloud }}"
#        id: "216196257331282583"
#      register: trusted_network_id

#    - name: Trusted Network by ID
#      ansible.builtin.debug:
#        msg: "{{ trusted_network_id }}"
