---
# zpa_segment_group_info.yml - Get details (ID and/or Name) of a segment group.
#
# Description
# ===========
#
# Quick example of how to use the 'zpa_segment_group' module to create a Segment Group in the ZPA Cloud.
#
# This playbook requires proper API credentials to be passed statically or via environment variables connection
# to the ZPA Cloud 'client_id', 'client_secret', customer_id and 'cloud'. These may be defined as host variables
# (see `host_vars/zpa_cloud.yml` for an example) or extra vars.
#
# Modules Used
# ============
#
# zpa_segment_group_info - https://zscaler.github.io/zpacloud-ansible/modules/zpa_segment_group_info_module.html
#
# Usage
# =====
#
#  $ ansible-playbook zpa_segment_group_info.yml

- name: Gather Details Segment Group Details
  hosts: localhost
  connection: local

  vars:
    zpa_cloud:
      client_id: "{{ client_id }}"
      client_secret: "{{ client_secret | default(omit) }}"
      customer_id: "{{ customer_id | default(omit) }}"
      cloud: "{{ cloud | default(omit) }}"

  tasks:
    - name: Gather Detail Information of All Segment Groups
      zscaler.zpacloud.zpa_segment_group_info:
        provider: "{{ zpa_cloud }}"
      register: segment_groups

    - name: All Segment Groups
      ansible.builtin.debug:
        msg: "{{ segment_groups }}"

    - name: Gather Details of All Segment Groups by Name
      zscaler.zpacloud.zpa_segment_group_info:
        provider: "{{ zpa_cloud }}"
        name: Example
      register: segment_group_name

    - name: Segment Groups by Name
      ansible.builtin.debug:
        msg: "{{ segment_group_name }}"

    - name: Gather Details of All Segment Groups by ID
      zscaler.zpacloud.zpa_segment_group_info:
        provider: "{{ zpa_cloud }}"
        id: "216196257331291969"
      register: segment_group_id

    - name: Segment Groups by ID
      ansible.builtin.debug:
        msg: "{{ segment_group_id }}"
